name: Run tests

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      strategy: ${{steps.load.outputs.strategy}}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: colcon/ci
      - id: load
        run: echo "strategy=$(echo $(cat strategy.json))" >> $GITHUB_OUTPUT

  pytest:
    needs: [setup]
    strategy: ${{fromJson(needs.setup.outputs.strategy)}}
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python}}
      - uses: colcon/ci@v1
      - uses: codecov/codecov-action@v3

  bootstrap:
    needs: [setup]
    strategy: ${{fromJson(needs.setup.outputs.strategy)}}
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python}}
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install -U -e .[test]
          python -m pip uninstall -y colcon-core
      - name: Build and test
        run: |
          cd ..
          python ${{github.workspace}}/bin/colcon build --paths ${{github.workspace}}
          python ${{github.workspace}}/bin/colcon test --paths ${{github.workspace}} --return-code-on-test-failure
      - name: Use the installed package (Bash)
        if: ${{runner.os != 'windows'}}
        shell: bash
        run: |
          . ../install/local_setup.sh
          colcon --help
      - name: Use the installed package (CMD)
        if: ${{runner.os == 'windows'}}
        shell: cmd
        run: |
          call ..\install\local_setup.bat
          colcon --help
