name: Run tests

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  pytest:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: [3.6, 3.7, 3.8, 3.9]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
      - uses: colcon/ci@v1
      - uses: codecov/codecov-action@v2

  bootstrap:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: [3.6, 3.7, 3.8, 3.9]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install -U -e .[test]
      - name: Build and test
        env:
          COLCON_ALL_SHELLS: True
        run: |
          python bin/colcon build --build-base ../build --install-base ../install
          python bin/colcon test --build-base ../build --install-base ../install
      - name: Use the installed package (Bash)
        shell: bash
        run: |
          . ../install/local_setup.sh
          colcon --help
      - name: Use the installed package (CMD)
        if: ${{runner.os == 'windows'}}
        shell: cmd
        run: |
          call ..\install\local_setup.bat
          colcon --help
