name: Run tests

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  pytest:
    uses: colcon/ci/.github/workflows/pytest.yaml@main
    with:
      codecov: true
  bootstrap:
    uses: ./.github/workflows/bootstrap.yaml
